-- AlterTable
ALTER TABLE "Domain" ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "Timestamp" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Interaction" ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "ModifiedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Model" ALTER COLUMN "ModifiedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Rating" ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "ModifiedAt" SET DATA TYPE TIMESTAMPTZ;
